ECWID-87001 make storename nonnull
Ecwid/ecwid-java-api-client pull request #142
Opened 2021-09-23 16:49 UTC by carlecwid

**Youtrack Story:** 
https://track.ecwid.com/youtrack/issue/ECWID-87001

**Description:** 
I have changed the store name property to not accept nullable values.

2021-10-04 08:47 UTC, Alexis2004 requested changes

2021-10-04 08:47 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/result/FetchedStoreProfile.kt
> +		val storeName: String? = "",
Shouldn't you also change field type from `String?` to `String`?

2022-01-18 08:36 UTC, Alexis2004 commented
@carlecwid, bump

2022-02-16 14:33 UTC, Alexis2004 commented
@carl, @turchenkoalex, этот PR ещё актуален? Если да, то нужно пофиксить замечание выше.

2022-02-16 14:36 UTC, turchenkoalex commented
Я бы закрыл этот PR как не нужный и опасный

2022-02-16 14:58 UTC, closed without merging