Add taxType to OrderItemTax
Ecwid/ecwid-java-api-client pull request #226
Opened 2022-10-26 08:25 UTC by aleskarova

2022-11-07 18:58 UTC, Alexis2004 requested changes

2022-11-07 18:58 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
> +		val taxType: OrderItemTaxType? = null,
А не нужно ли поле `taxType` поднять в родительский тип `BaseOrderTax`? Как будто бы оно используется во всех наследниках.

2022-11-07 18:58 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt
> +	AllowNullable(FetchedOrder.BaseOrderItemTax::taxType),
А новое поле точно может быть null'овым?

2022-11-14 12:27 UTC, aleskarova commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedOrderRules.kt
> +	AllowNullable(FetchedOrder.BaseOrderItemTax::taxType),
Да, может. Для налогов из стран, кроме США, на данный момент это поле будет null.

2022-11-14 12:29 UTC, aleskarova commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/order/result/FetchedOrder.kt
> +		val taxType: OrderItemTaxType? = null,
Не используется в `HandlingFeeTax` (который тоже наследник `BaseOrderTax`).

2022-11-18 09:09 UTC, Alexis2004 approved these changes

2022-11-18 09:09 UTC, merged