ECWID-109995 Custom Order Statuses: new API for custom order statuses
Ecwid/ecwid-java-api-client pull request #236
Opened 2022-11-27 11:58 UTC by winrokru

Api для [ECWID-109995](https://track.ecwid.com/youtrack/issue/ECWID-109995) Custom Order Statuses: API /order_statuses

2022-12-12 10:15 UTC, elviswarlock requested changes
Лучше заменить использование Setting -> Settings, так как у нас много настроек и в единственном числе лучше не употреблять.
А точно у нас в API поля: defaultStatus, name, nameTranslations должны быть nullable?

2022-12-12 10:43 UTC, winrokru commented
> Лучше заменить использование Setting -> Settings, так как у нас много настроек и в единственном числе лучше не употреблять. А точно у нас в API поля: defaultStatus, name, nameTranslations должны быть nullable?

1)Я в самом Api использую для одного кастомного статуса OrderStatusSetting , если они приходят в списке то 
OrderStatusesSetting , то есть у мне множественное число Statuses, если дословно настройка статусов заказов.
Все сделано в единой стилистике и в api и vue, поэтому лучше оставить так.
2)Да эти поля: defaultStatus, name, nameTranslations могут быть nullable , так как можем передавать не все , а одно из них

2022-12-12 10:54 UTC, winrokru commented
тоесть за основу взял entity OrderStatusSetting.kt в базе таблица "order_status_setting" (настройка статуса заказа), если возвращаем список этих самых entity , то юзаем getOrderStatus**es**Setting (настройку статус**ов** заказа)

2022-12-13 10:12 UTC, elviswarlock approved these changes

2022-12-13 10:21 UTC, merged