ECWID-110192 - add create and delete payment option API methods
Ecwid/ecwid-java-api-client pull request #258
Opened 2023-02-22 09:24 UTC by alxzoomer

2023-02-24 08:12 UTC, kurguzov requested changes

2023-02-24 08:12 UTC, kurguzov commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClient.kt
>  	// 	fun addPaymentOption()
А чем createPaymentOption отличается от addPaymentOption?

2023-02-24 08:12 UTC, kurguzov commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClient.kt
>  	// 	fun updatePaymentOption()
Давай для add/update тоже сразу методы добавим в api-client'а

2023-02-24 08:12 UTC, kurguzov commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedStoreProfile.kt
> +		enabled = enabled,
как будто не хватает поля сonfigured, которое я добавлял совсем недавно. У тебя неактуальная база, или ты его не заметил?

2023-02-24 08:12 UTC, kurguzov commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/request/UpdatedPaymentOption.kt
> +	val enabled: Boolean? = null,
configured

2023-02-24 10:22 UTC, alxzoomer commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClient.kt
>  	// 	fun updatePaymentOption()
add это createPaymentOption. update добавил

2023-02-24 11:39 UTC, alxzoomer commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedStoreProfile.kt
> +		enabled = enabled,
Подсматривал в апи док, чего там нет не добавлял. Теперь добавил.

2023-02-24 11:39 UTC, alxzoomer commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/profile/request/UpdatedPaymentOption.kt
> +	val enabled: Boolean? = null,
и здесь добавил

2023-02-27 12:42 UTC, kurguzov approved these changes

2023-02-27 12:43 UTC, kurguzov approved these changes

2023-02-27 12:43 UTC, kurguzov approved these changes

2023-02-27 12:44 UTC, merged