ECWID-116124 - add video info to product media
Ecwid/ecwid-java-api-client pull request #271
Opened 2023-03-17 10:04 UTC by kitty-ecwid

2023-03-21 10:13 UTC, Alexis2004 requested changes

2023-03-21 10:13 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
> +		val videoCoverId: String? = null,
А давай посмотрим, может ли APIv3 возвращать в этих полях null или нет. Везде, где не может, уберём `?` у типов.

2023-03-22 10:36 UTC, kitty-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
> +		val videoCoverId: String? = null,
По бизнес-логике null не должно быть в полях url и embedHtml, но сейчас APIv3 может вернуть по ним null. Нужно в этом случае что-то править?

2023-03-28 16:08 UTC, qblake commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
> +		val videoCoverId: String? = null,
>но сейчас APIv3 может вернуть по ним null

получается это какое-то поведение не соответствующее бизнес-логике? или какие-то невалидные данные?

2023-03-29 06:54 UTC, kitty-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/dto/product/result/FetchedProduct.kt
> +		val videoCoverId: String? = null,
Невалидные данные, например если вручную править в базе. И я не знаю что делать с такими данными

2023-04-05 13:47 UTC, merged