ECWID-124999 - add OrderItem.combinationId
Ecwid/ecwid-java-api-client pull request #315
Opened 2023-08-08 11:34 UTC by mplain

2023-08-08 11:41 UTC, zenon-ecwid approved these changes

2023-08-09 06:04 UTC, Alexis2004 requested changes
Может быть лучше `variationId`? Комбинации – это старое название сущности, для пользователей мы их теперь называем вариациями.

2023-08-09 07:37 UTC, zenon-ecwid commented
> Может быть лучше variationId? Комбинации – это старое название сущности, для пользователей мы их теперь называем вариациями.

Ты уверен что стоит в существующем API менять этот нейминг? В API мы уже называем эту сущность Combination и добавление альтернативного названия внесет еще больше путаницы. Кроме того, сами поля добавлены больше года назад.

2023-08-09 07:40 UTC, Alexis2004 commented
> > Может быть лучше variationId? Комбинации – это старое название сущности, для пользователей мы их теперь называем вариациями.
> 
> Ты уверен что стоит в существующем API менять этот нейминг? В API (в названиях полей и в URL) мы уже называем эту сущность combination и добавление альтернативного названия внесет еще больше путаницы. Кроме того, сами поля добавлены больше года назад.

Интересно. Я просто посмотрел на эндпойнты /variation, там это вариации. Но в куче других мест – да, названо по-прежнему комбинациями. Окей, если это не новое поле для API, а лишь новое поле для клиента, то давайте оставим такой нейминг.

2023-08-09 07:47 UTC, merged