Response fields improve
Ecwid/ecwid-java-api-client pull request #330
Opened 2023-09-22 05:37 UTC by basiliscus

2023-10-09 09:58 UTC, turchenkoalex approved these changes

2023-10-09 09:58 UTC, turchenkoalex commented on src/main/kotlin/com/ecwid/apiclient/v3/responsefields/ResponseFieldsProvider.kt
> +		ResponseFieldsBuilder().buildResponseFields(partialResultClass)
А может и ResponseFieldsBuilder создадим один раз для этого метода?
Он ThreadSafe. Накладные расходы будут но не значительные, это может быть полезно для разбора внутренних структур

2023-10-09 13:25 UTC, Alexis2004 requested changes

2023-10-09 13:25 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/CategoriesApiClientImpl.kt
> +	}
Я бы предпочёл, чтобы partial-методы располагались бы рядом с одноимёнными полными. Так будет сразу видно, для каких методов есть partial пара, а для каких её забыли добавить.

2023-10-09 13:25 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/ProductsApiClientImpl.kt
> +	}
И кстати, а то что partial и не partial-методы имеют разное имя – это обусловленно каким-то техническим ограничением?

2023-10-09 13:25 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +			responseFieldsOverride = responseFieldsOf(baseResultClass) + responseFieldsOf(extResultClass),
А мы нормально отработаем в том случае, если Ext-сущность частично перекрывает основную? Например storeProfile.account.XXX и storeProfile.account.YYY в основной сущности и storeProfile.account.ZZZ в расширенной?

2023-10-09 13:57 UTC, turchenkoalex commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +			responseFieldsOverride = responseFieldsOf(baseResultClass) + responseFieldsOf(extResultClass),
позволю ответить кодом
тут скорее всего про то как работают сами responseFields, их реализация уже была сделана

этот тест проходит, но в коде прям такого сейчас нет
```
@Test
	fun `plus operator test2`() {
		val first = newResponseFields {
			field("account") {
				field("XXXX")
				field("YYYY")
			}
		}

		val second = newResponseFields {
			field("account") {
				field("ZZZZ")
			}
		}

		val expected = newResponseFields {
			field("account") {
				field("XXXX")
				field("YYYY")
				field("ZZZZ")
			}
		}

		assertEquals(expected, first + second)
		assertEquals(expected, second + first)
	}
```

2023-10-09 14:17 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/ProductsApiClientImpl.kt
> +	}
Обрати внимание, что я тут веду речь не про extension-функцию, а про перегрузку метода с двумя аргументами

2023-10-09 14:17 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +			responseFieldsOverride = responseFieldsOf(baseResultClass) + responseFieldsOf(extResultClass),
Понятно, спасибо!

2023-10-09 14:20 UTC, turchenkoalex commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/CategoriesApiClientImpl.kt
> +	}
мне ок любой вариант.

2023-10-09 14:29 UTC, basiliscus commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/ProductsApiClientImpl.kt
> +	}
Метод с двумя аргументами можно назвать без суффикса.
Но extension-функции придется суффикс дорисовать, а раз так, то лучше и функцию-член так же назвать.

2023-10-09 18:16 UTC, basiliscus commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/CategoriesApiClientImpl.kt
> +	}
Done

2023-10-09 18:16 UTC, basiliscus commented on src/main/kotlin/com/ecwid/apiclient/v3/impl/ProductsApiClientImpl.kt
> +	}
Done

2023-10-09 18:17 UTC, basiliscus commented on src/main/kotlin/com/ecwid/apiclient/v3/responsefields/ResponseFieldsProvider.kt
> +	if (!partialResultType.isMarkedNullable && fullResultType.isMarkedNullable) {
!

2023-10-10 06:31 UTC, Alexis2004 approved these changes

2023-10-10 07:02 UTC, turchenkoalex approved these changes

2023-10-10 07:42 UTC, merged