ECWID-128538 - add tracking url to order
Ecwid/ecwid-java-api-client pull request #346
Opened 2023-10-31 09:27 UTC by nerevar-ecwid

2023-11-01 12:18 UTC, Alexis2004 requested changes

2023-11-01 12:18 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/NonUpdatablePropertyRules.kt
> +	Ignored(FetchedCart::trackingUrl),
Не нужно добавлять новых полей как Ignored. Нужно или использовать ненулловые поля, или если это требуется согласно бизнес-логике помечать поля как AllowedNullable

2023-11-01 12:18 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
> +		trackingUrl = trackingUrl ?: "https://track.aftership.com/$trackingNumber",
Не понятно, зачем тут нужно указывать дефолт. Этот дефолт должен приходить в готовом виде из APIv3 или мы должны фолбечиться на него в явном виде в местах использования в конечном коде

2023-11-01 12:25 UTC, nerevar-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
> +		trackingUrl = trackingUrl ?: "https://track.aftership.com/$trackingNumber",
фактически это для тестов, юнит тесты сейчас делают запрос на апи и получают null ( потому что в апигейте нет такого поля еще), а потом тут будет приходить уже значение (проверил тесты с изменениями в апигейте и без)

2023-11-01 14:12 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
> +		trackingUrl = trackingUrl ?: "https://track.aftership.com/$trackingNumber",
Ну по хорошему тут нужно сначала отрелизить изменения в апигейте. Ну или хотя бы потом отдельным PRом этот костыль. Если обещаешь пофиксить после релиза, то я приму как есть.

2023-11-01 14:13 UTC, Alexis2004 requested changes

2023-11-01 14:13 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/DtoContractUnitTest.kt
> +		assertEquals(977, ignoreNullablePropertiesCount) {
Здесь нужно вернуть число?

2023-11-01 14:13 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedCartRules.kt
> +	IgnoreNullable(FetchedCart::trackingUrl),
Ignore => Allow?

2023-11-02 08:11 UTC, nerevar-ecwid commented on src/test/kotlin/com/ecwid/apiclient/v3/DtoContractUnitTest.kt
> +		assertEquals(977, ignoreNullablePropertiesCount) {
тесты прошли, значит тут все ок

2023-11-02 08:12 UTC, nerevar-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/converter/FetchedOrder.kt
> +		trackingUrl = trackingUrl ?: "https://track.aftership.com/$trackingNumber",
да, сначала бы апигейт зарелизить, но это слишком долго, заведу себе тикет на допил этого после релиза

2023-11-02 08:13 UTC, nerevar-ecwid commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedCartRules.kt
> +	IgnoreNullable(FetchedCart::trackingUrl),
это корзина, тут по идее Ignore

2023-11-02 11:13 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/DtoContractUnitTest.kt
> +		assertEquals(977, ignoreNullablePropertiesCount) {
Тесты пройдут и на числе миллион. Ты своим изменением разрешил кому-то безнаказанно создать новое поле и пометить его как Ignore

2023-11-02 11:15 UTC, Alexis2004 commented on src/test/kotlin/com/ecwid/apiclient/v3/rule/nullablepropertyrules/FetchedCartRules.kt
> +	IgnoreNullable(FetchedCart::trackingUrl),
Нет, новых Ignore кроме тех которые были на момент написания теста появляться не должно. В светлом будущем нужно все старые Ignore будет заменить на Allow или сделать не nullable'ными, где возможно.

2023-11-02 11:15 UTC, Alexis2004 requested changes
См. комменты

2023-11-02 11:28 UTC, Alexis2004 approved these changes

2023-11-02 11:38 UTC, merged