ECWID-144513 startersite error Caused by IllegalStateException: Expected but was STRING at line column path at JsonReader.beginObject(JsonReader.java:) - removed unused imports
Ecwid/ecwid-java-api-client pull request #426
Opened 2024-08-12 12:07 UTC by bubalekh

2024-08-15 10:35 UTC, soer-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
а тут js array не приходят?

2024-08-15 10:50 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Судя по коду - нет, не приходят. Ошибка - это JSON Object

2024-08-26 10:54 UTC, soer-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
нет способа покрасивее как-то это оформить?
нет isJSON методов? и как мы логируем ошибку балансера?

2024-08-26 11:19 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Из коробки дешевле способа нет, можно сделать `try {JSONObject(responseBody)}` и это будет безопасней, но дороже (таких ошибок у нас мало, а вот 2 преобразования вместо одного на каждый запрос - это очень дорого)
Метод `startsWith` почти ничего не стоит

2024-08-26 11:20 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Ошибки балансера логируются как обычные

2024-08-27 07:48 UTC, soer-ecwid commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
давай дороже и безопаснее

2024-08-29 11:42 UTC, soer-ecwid approved these changes

2024-09-19 07:38 UTC, Alexis2004 requested changes

2024-09-19 07:38 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Я что-то не понял этого твиста. А почему бы просто не обернуть десериализацию в try/catch и в ветке catch не считать что у нас просто нет деталей об ошибке (возвращать null)?

2024-09-19 10:38 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Выброс и обработка exception в Java - одна из самых дорогих процедур, а вот проверить первый символ гарантировано ненуловой строки - это очень быстро и дешево

2024-09-19 12:01 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Я сейчас вообще склоняюсь вот к такому:

```
override fun <V> deserializeOrNull(json: String, clazz: Class<V>): V? {
		return try {
			return gson.fromJson(json, clazz)
		} catch (e: JsonParseException) {
			null
		}
	}
```

2024-09-19 12:26 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Но это дорого (потому что ошибки балансера - вещь частая)

2024-09-19 15:50 UTC, Alexis2004 commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
Пока ошибок не сотни в секунду, накладными расходами можно пренебречь.
Ну и не туда оптимизируешь, нужно не парсинг ошибок ускорять, а разбираться чем вызваны ошибки и чинить их – API должно работать без ошибок.

2024-09-20 06:37 UTC, bubalekh commented on src/main/kotlin/com/ecwid/apiclient/v3/ApiClientHelper.kt
> +					val ecwidError = if (responseBody.isNotBlank() && responseBody.startsWith("{")) {
@Alexis2004 запушил максимально минимальную имплементацию фикса

2024-09-26 08:57 UTC, Alexis2004 approved these changes

2024-09-26 08:57 UTC, merged